from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import stat
import uuid

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

import licensing


DEFAULT_PRIVATE_KEY_PATH = "license_private_key.pem"
DEFAULT_PUBLIC_MODULE_PATH = "license_public_key.py"


def load_private_key(private_key_path: str) -> Ed25519PrivateKey:
    with open(private_key_path, "rb") as f:
        private_key = serialization.load_pem_private_key(f.read(), password=None)

    if not isinstance(private_key, Ed25519PrivateKey):
        raise ValueError("Private key is not an Ed25519 key.")

    return private_key


def write_private_key(private_key: Ed25519PrivateKey, private_key_path: str) -> None:
    private_bytes = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    with open(private_key_path, "wb") as f:
        f.write(private_bytes)

    try:
        os.chmod(private_key_path, stat.S_IRUSR | stat.S_IWUSR)
    except OSError:
        pass


def public_key_pem(private_key: Ed25519PrivateKey) -> str:
    public_bytes = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    return public_bytes.decode("utf-8")


def write_public_module(public_module_path: str, public_pem: str) -> None:
    with open(public_module_path, "w", encoding="utf-8") as f:
        f.write("# Generated by license_tool.py init-keys.\n")
        f.write("PUBLIC_KEY_PEM = ")
        f.write(repr(public_pem))
        f.write("\n")


def init_keys(args: argparse.Namespace) -> None:
    if os.path.exists(args.private_key) and not args.force:
        private_key = load_private_key(args.private_key)
    else:
        private_key = Ed25519PrivateKey.generate()
        write_private_key(private_key, args.private_key)

    write_public_module(args.public_module, public_key_pem(private_key))
    print(f"Private key: {args.private_key}")
    print(f"Public key module: {args.public_module}")
    print("Keep the private key secret. Do not send it with the app.")


def create_license(args: argparse.Namespace) -> None:
    private_key = load_private_key(args.private_key)
    issued_at = dt.date.today().isoformat()
    expires_at = args.expires.strip() if args.expires else None
    if expires_at:
        dt.date.fromisoformat(expires_at)

    payload = {
        "license_id": args.license_id or str(uuid.uuid4()),
        "name": args.name.strip(),
        "device_id": args.device_id.strip().upper(),
        "issued_at": issued_at,
        "expires_at": expires_at,
    }
    payload_bytes = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    payload_segment = licensing.b64url_encode(payload_bytes)
    signature_segment = licensing.b64url_encode(private_key.sign(payload_segment.encode("ascii")))
    license_token = f"{licensing.LICENSE_VERSION}.{payload_segment}.{signature_segment}"

    if args.output:
        os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(license_token)
            f.write("\n")

    print(license_token)


def show_device_id(_: argparse.Namespace) -> None:
    print(licensing.get_device_id())


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Offline license tool for FacebookPageScheduler.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init-keys", help="Create a private key and app public key module.")
    init_parser.add_argument("--private-key", default=DEFAULT_PRIVATE_KEY_PATH)
    init_parser.add_argument("--public-module", default=DEFAULT_PUBLIC_MODULE_PATH)
    init_parser.add_argument("--force", action="store_true", help="Replace an existing private key.")
    init_parser.set_defaults(func=init_keys)

    create_parser = subparsers.add_parser("create", help="Create a signed license for a Device ID.")
    create_parser.add_argument("--private-key", default=DEFAULT_PRIVATE_KEY_PATH)
    create_parser.add_argument("--device-id", required=True)
    create_parser.add_argument("--name", required=True)
    create_parser.add_argument("--expires", help="Optional expiration date in YYYY-MM-DD format.")
    create_parser.add_argument("--license-id", help="Optional custom license ID.")
    create_parser.add_argument("--output", help="Optional file path to write the license token.")
    create_parser.set_defaults(func=create_license)

    device_parser = subparsers.add_parser("device-id", help="Print this computer's Device ID.")
    device_parser.set_defaults(func=show_device_id)

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
