from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import stat
import uuid

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

import licensing


DEFAULT_PRIVATE_KEY_PATH = "license_private_key.pem"
DEFAULT_PUBLIC_MODULE_PATH = "license_public_key.py"
DEFAULT_LICENSE_LOG_PATH = os.path.join("licenses", "issued_licenses.jsonl")


def load_private_key(private_key_path: str) -> Ed25519PrivateKey:
    with open(private_key_path, "rb") as f:
        private_key = serialization.load_pem_private_key(f.read(), password=None)

    if not isinstance(private_key, Ed25519PrivateKey):
        raise ValueError("Private key is not an Ed25519 key.")

    return private_key


def write_private_key(private_key: Ed25519PrivateKey, private_key_path: str) -> None:
    private_bytes = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    with open(private_key_path, "wb") as f:
        f.write(private_bytes)

    try:
        os.chmod(private_key_path, stat.S_IRUSR | stat.S_IWUSR)
    except OSError:
        pass


def public_key_pem(private_key: Ed25519PrivateKey) -> str:
    public_bytes = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    return public_bytes.decode("utf-8")


def write_public_module(public_module_path: str, public_pem: str) -> None:
    with open(public_module_path, "w", encoding="utf-8") as f:
        f.write("# Generated by license_tool.py init-keys.\n")
        f.write("PUBLIC_KEY_PEM = ")
        f.write(repr(public_pem))
        f.write("\n")


def init_keys(args: argparse.Namespace) -> None:
    if os.path.exists(args.private_key) and not args.force:
        private_key = load_private_key(args.private_key)
    else:
        private_key = Ed25519PrivateKey.generate()
        write_private_key(private_key, args.private_key)

    write_public_module(args.public_module, public_key_pem(private_key))
    print(f"Private key: {args.private_key}")
    print(f"Public key module: {args.public_module}")
    print("Keep the private key secret. Do not send it with the app.")


def create_license(args: argparse.Namespace) -> None:
    private_key = load_private_key(args.private_key)
    issued_at = dt.date.today().isoformat()
    expires_at = args.expires.strip() if args.expires else None
    if expires_at:
        dt.date.fromisoformat(expires_at)

    payload = {
        "license_id": args.license_id or str(uuid.uuid4()),
        "name": args.name.strip(),
        "device_id": args.device_id.strip().upper(),
        "issued_at": issued_at,
        "expires_at": expires_at,
    }
    payload_bytes = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    payload_segment = licensing.b64url_encode(payload_bytes)
    signature_segment = licensing.b64url_encode(private_key.sign(payload_segment.encode("ascii")))
    license_token = f"{licensing.LICENSE_VERSION}.{payload_segment}.{signature_segment}"

    if args.output:
        os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(license_token)
            f.write("\n")

    if args.log:
        append_license_log(args.log, payload, license_token, args.output)

    print(license_token)


def append_license_log(
    log_path: str,
    payload: dict[str, object],
    license_token: str,
    output_path: str | None,
) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(log_path)), exist_ok=True)
    record = {
        **payload,
        "created_at": dt.datetime.now().isoformat(timespec="seconds"),
        "license": license_token,
        "output": output_path,
    }
    with open(log_path, "a", encoding="utf-8") as f:
        f.write(json.dumps(record, sort_keys=True))
        f.write("\n")


def load_license_log(log_path: str) -> list[dict[str, object]]:
    records = []
    if not os.path.exists(log_path):
        return records

    with open(log_path, "r", encoding="utf-8") as f:
        for line_number, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue

            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                print(f"Skipping invalid log line {line_number}.")
                continue

            if isinstance(record, dict):
                records.append(record)

    return records


def list_licenses(args: argparse.Namespace) -> None:
    records = load_license_log(args.log)
    if not records:
        print(f"No licenses found in {args.log}.")
        return

    if args.full:
        print(json.dumps(records, indent=2, sort_keys=True))
        return

    print(f"{'Issued':<19} {'Name':<24} {'Expires':<12} {'Device ID':<24} License ID")
    print("-" * 100)
    for record in records:
        created_at = str(record.get("created_at", ""))[:19]
        name = str(record.get("name", ""))[:24]
        expires_at = str(record.get("expires_at") or "never")[:12]
        device_id = str(record.get("device_id", ""))[:24]
        license_id = str(record.get("license_id", ""))
        print(f"{created_at:<19} {name:<24} {expires_at:<12} {device_id:<24} {license_id}")


def show_device_id(_: argparse.Namespace) -> None:
    print(licensing.get_device_id())


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Offline license tool for FacebookPageScheduler.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init-keys", help="Create a private key and app public key module.")
    init_parser.add_argument("--private-key", default=DEFAULT_PRIVATE_KEY_PATH)
    init_parser.add_argument("--public-module", default=DEFAULT_PUBLIC_MODULE_PATH)
    init_parser.add_argument("--force", action="store_true", help="Replace an existing private key.")
    init_parser.set_defaults(func=init_keys)

    create_parser = subparsers.add_parser("create", help="Create a signed license for a Device ID.")
    create_parser.add_argument("--private-key", default=DEFAULT_PRIVATE_KEY_PATH)
    create_parser.add_argument("--device-id", required=True)
    create_parser.add_argument("--name", required=True)
    create_parser.add_argument("--expires", help="Optional expiration date in YYYY-MM-DD format.")
    create_parser.add_argument("--license-id", help="Optional custom license ID.")
    create_parser.add_argument("--output", help="Optional file path to write the license token.")
    create_parser.add_argument(
        "--log",
        default=DEFAULT_LICENSE_LOG_PATH,
        help="License history path. Use --log '' to skip logging.",
    )
    create_parser.set_defaults(func=create_license)

    device_parser = subparsers.add_parser("device-id", help="Print this computer's Device ID.")
    device_parser.set_defaults(func=show_device_id)

    list_parser = subparsers.add_parser("list", help="List generated licenses from the local log.")
    list_parser.add_argument("--log", default=DEFAULT_LICENSE_LOG_PATH)
    list_parser.add_argument("--full", action="store_true", help="Print full JSON records.")
    list_parser.set_defaults(func=list_licenses)

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
